# Site settings
title: oadussang's CV 
description: Oadussang's CV
favicon: /assets/img/favicon.ico
baseurl: http://klonima.net
url: http://klonima.net
rss_url: /pages/atom.xml
google_analytics: UA-64313986-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Oscar Andres Dussan Garcia
  title: Backend Developer
  address: Bogota, Colombia
  email: oadussang@gmail.com
  link: http://klonima.net
  weibo:
  github: oadussang
  linkedin: oscardu
  twitter: oscardu
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
  stackoverflow: 2383327
  workHistory:
    - work1:
      company: Serviradar SAS
      location: Bogota, Colombia
      title: Co-Founder and Lead Developer
      started: 2014
      duration: (2014 - Present)
      description:                                                                                                              .
    - work2:
      company: Dynaco 
      location: Bogota, Colombia
      title: BackEnd, FrontEnd and Android Developer
      started: 2011
      duration: (2011 - 2013)
      description:                                                                                                              .
  educationHistory:
    - education1:
      organization: Universidad Nacional de Colombia
      location: Bogota, Colombia
      degree: Bachelor
      major: Computer and Systems Engineer
      started: 2008
      #duration: (2005 - 2009)
      description:                                                                                                               .
  languages:
    - language1:
      name: Spanish
      proficiency: Native
    - language2:
      name: English
      proficiency: Limited    
  programmingSkills:
    - skill1:
      name: Python, Django Framework (BE)
      percentage: 80%
    - skill2:
      name: JavaScript - Expressjs (BE)
      percentage: 60%
    - skill3:
      name: C# - .NET Framework (BE)
      percentage: 70%
    - skill4:
      name: PHP (BE)
      percentage: 40%
    - skill5:
      name: Javascript - AngularJS (FE)
      percentage: 30%
    - skill6:
      name: HTML, CSS (FE)
      percentage: 80%
    - skill7:
      name: Java SE
      percentage: 90%
